In [1]:
import pandas as pd
import numpy as np
info = np.array(['p','a','n','d','s'])
a= pd.Series(info)
print(a)

0    p
1    a
2    n
3    d
4    s
dtype: object


In [3]:
import pandas as pd
import numpy as np
a = pd.Series(['java','c','c++', np.nan])
a.map({'java':'core'})


0    core
1     NaN
2     NaN
3     NaN
dtype: object

In [6]:
s = pd.Series(['a','b','c'], name="vals")
s.to_frame()

vals
0    a
1    b
2    c

In [10]:
import array
arr = array.array('l',[2,4,6,8,10,12])
print("new created array:",end="")
for l in range (0,len(arr)):
    print(arr[l],end=" ")
    print(arr[l], end="")
    print("\r")

new created array:2 2
4 4
6 6
8 8
10 10
12 12


In [16]:
import pandas as pd
dict ={'name':["salma","surbhi","arkita","sherya","khusi"],
       'age':['20','19','18','21','17']}
info = pd.DataFrame(dict,index =[True,True,False,True,True])
print(info)

         name age
True    salma  20
True   surbhi  19
False  arkita  18
True   sherya  21
True    khusi  17


In [18]:
import numpy as np

# Create the original array
arr = np.arange(16)
print('The original array is: \n', arr)

# Reshape the array into a 2x8 matrix
arr = arr.reshape(2, 8)
print("\nReshaped array:\n", arr)

# Reshape the array into a 8x2 matrix
arr = arr.reshape(8, 2)
print("\nReshaped array:\n", arr)

The original array is: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Reshaped array:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

Reshaped array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
